# Merged with ./docker-compose.yml
services:
  server-api:
    # Linux users can lower cpu usage by removing the --legacy-watch flag
    command: /app/node_modules/.bin/nodemon --legacy-watch --watch dist dist/main.js
    # command: /app/node_modules/.bin/nodemon --inspect=0.0.0.0:9229 --legacy-watch --watch dist dist/main.js

    # Put your secrets (e.g. API keys) to the .env file
    # env_file:
    #   - .env

  storage-main:
    command: npm run migrate:latest:dev